language: php

php:
 - 7.0.10

branches:
 - master

before_script:
 - cd /home/travis/build/
 - phpenv config-rm xdebug.ini
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0RC8
 - git clone --depth=50 --branch=php7 https://github.com/ClearSkyTeam/ClearSky.git
 - mkdir -p ClearSky/plugins/GuessTheNumber-src
 - cp -rf SalmonGER/GuessTheNumber/src ClearSky/plugins/GuessTheNumber-src
 - cp -rf SalmonGER/GuessTheNumber/resources ClearSky/plugins/GuessTheNumber-src
 - cp -rf SalmonGER/GuessTheNumber/plugin.yml ClearSky/plugins/GuessTheNumber-src
 - cp -rf SalmonGER/GuessTheNumber/LICENSE ClearSky/plugins/GuessTheNumber-src
 - cp -rf SalmonGER/GuessTheNumber/build.php ClearSky/
 - cd ClearSky/plugins/
 - wget -O DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar
 - cd /home/travis/build/ClearSky

script:
 - php build.php

deploy:
  provider: releases
  api_key: "$traviskey"
  file: "/home/travis/build/ClearSky/plugins/DevTools/GuessTheNumber.phar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false

notifications:
 email: false
